# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

poisson_disc_sampling <- function(radius, size_x, size_y, num_samples_before_rejection = 30L) {
    .Call(`_poissonDiscSampling_poisson_disc_sampling`, radius, size_x, size_y, num_samples_before_rejection)
}

